// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AnimationCurve 用于存储 Keyframe 数组
 * AnimationCurve stores a Keyframe array
 */
export class AnimationCurve {
    /**
     * 按时间保存的关键帧 / Keyframes stored in time order
     */
    "Keyframes": Keyframe[];

    /** Creates a new AnimationCurve instance. */
    constructor($$source: Partial<AnimationCurve> = {}) {
        if (!("Keyframes" in $$source)) {
            this["Keyframes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AnimationCurve instance from a string or object.
     */
    static createFrom($$source: any = {}): AnimationCurve {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Keyframes" in $$parsedSource) {
            $$parsedSource["Keyframes"] = $$createField0_0($$parsedSource["Keyframes"]);
        }
        return new AnimationCurve($$parsedSource as Partial<AnimationCurve>);
    }
}

/**
 * Keyframe 与 UnityEngine.Keyframe 对应
 * Keyframe corresponds to UnityEngine.Keyframe
 */
export class Keyframe {
    /**
     * 关键帧时间 / Keyframe time
     */
    "Time": number;

    /**
     * 关键帧值 / Keyframe value
     */
    "Value": number;

    /**
     * 入切线 / Incoming tangent
     */
    "InTangent": number;

    /**
     * 出切线 / Outgoing tangent
     */
    "OutTangent": number;

    /** Creates a new Keyframe instance. */
    constructor($$source: Partial<Keyframe> = {}) {
        if (!("Time" in $$source)) {
            this["Time"] = 0;
        }
        if (!("Value" in $$source)) {
            this["Value"] = 0;
        }
        if (!("InTangent" in $$source)) {
            this["InTangent"] = 0;
        }
        if (!("OutTangent" in $$source)) {
            this["OutTangent"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Keyframe instance from a string or object.
     */
    static createFrom($$source: any = {}): Keyframe {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Keyframe($$parsedSource as Partial<Keyframe>);
    }
}

/**
 * Nei 表示解密后的 .nei CSV 表格数据
 * Nei represents decrypted .nei CSV table data
 */
export class Nei {
    /**
     * CSV 的行数 / Number of CSV rows
     */
    "Rows": number;

    /**
     * CSV 的列数 / Number of CSV columns
     */
    "Cols": number;

    /**
     * CSV 的数据 [行][列] / CSV cell data indexed as [row][column]
     */
    "Data": string[][];

    /** Creates a new Nei instance. */
    constructor($$source: Partial<Nei> = {}) {
        if (!("Rows" in $$source)) {
            this["Rows"] = 0;
        }
        if (!("Cols" in $$source)) {
            this["Cols"] = 0;
        }
        if (!("Data" in $$source)) {
            this["Data"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Nei instance from a string or object.
     */
    static createFrom($$source: any = {}): Nei {
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Data" in $$parsedSource) {
            $$parsedSource["Data"] = $$createField2_0($$parsedSource["Data"]);
        }
        return new Nei($$parsedSource as Partial<Nei>);
    }
}

/**
 * PanierRadiusGroup 存储骨骼特定的半径信息
 * PanierRadiusGroup stores bone-specific radius information
 */
export class PanierRadiusGroup {
    /**
     * 骨骼名称 / Bone name
     */
    "BoneName": string;

    /**
     * 该骨骼的裙撑半径 / Panier radius for this bone
     */
    "Radius": number;

    /**
     * 半径分布曲线 / Radius distribution curve
     */
    "Curve": AnimationCurve;

    /** Creates a new PanierRadiusGroup instance. */
    constructor($$source: Partial<PanierRadiusGroup> = {}) {
        if (!("BoneName" in $$source)) {
            this["BoneName"] = "";
        }
        if (!("Radius" in $$source)) {
            this["Radius"] = 0;
        }
        if (!("Curve" in $$source)) {
            this["Curve"] = (new AnimationCurve());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PanierRadiusGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): PanierRadiusGroup {
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Curve" in $$parsedSource) {
            $$parsedSource["Curve"] = $$createField2_0($$parsedSource["Curve"]);
        }
        return new PanierRadiusGroup($$parsedSource as Partial<PanierRadiusGroup>);
    }
}

/**
 * Psk 整体描述一个 .psk 文件的结构
 * Psk describes the full structure of a .psk file
 */
export class Psk {
    /**
     * 文件签名，通常为 CM3D21_PSK / File signature, usually CM3D21_PSK
     */
    "Signature": string;

    /**
     * 文件版本号，可能随游戏更新变化但结构不一定变化 / File version, may change with game updates without structural changes
     */
    "Version": number;

    /**
     * 裙撑半径 / Panier radius
     */
    "PanierRadius": number;

    /**
     * 裙撑半径分布曲线 / Panier radius distribution curve
     */
    "PanierRadiusDistrib": AnimationCurve;

    /**
     * 裙撑半径分布组 / Panier radius distribution groups
     */
    "PanierRadiusDistribGroups": PanierRadiusGroup[];

    /**
     * 裙撑力度 / Panier force
     */
    "PanierForce": number;

    /**
     * 裙撑力度分布曲线 / Panier force distribution curve
     */
    "PanierForceDistrib": AnimationCurve;

    /**
     * 裙撑应力 / Panier stress force
     */
    "PanierStressForce": number;

    /**
     * 最小应力度 / Minimum stress degree
     */
    "StressDegreeMin": number;

    /**
     * 最大应力度 / Maximum stress degree
     */
    "StressDegreeMax": number;

    /**
     * 最小应力缩放 / Minimum stress scale
     */
    "StressMinScale": number;

    /**
     * 缩放平滑速度 / Scale easing speed
     */
    "ScaleEaseSpeed": number;

    /**
     * 裙撑力度距离阈值 / Panier force distance threshold
     */
    "PanierForceDistanceThreshold": number;

    /**
     * 计算时间 / Calculation time
     */
    "CalcTime": number;

    /**
     * 速度力率 / Velocity force rate
     */
    "VelocityForceRate": number;

    /**
     * 速度力率分布曲线 / Velocity force rate distribution curve
     */
    "VelocityForceRateDistrib": AnimationCurve;

    /**
     * 重力向量 / Gravity vector
     */
    "Gravity": Vector3;

    /**
     * 重力分布曲线 / Gravity distribution curve
     */
    "GravityDistrib": AnimationCurve;

    /**
     * 硬度值数组 / Hardness value array
     */
    "HardValues": number[];

    /** Creates a new Psk instance. */
    constructor($$source: Partial<Psk> = {}) {
        if (!("Signature" in $$source)) {
            this["Signature"] = "";
        }
        if (!("Version" in $$source)) {
            this["Version"] = 0;
        }
        if (!("PanierRadius" in $$source)) {
            this["PanierRadius"] = 0;
        }
        if (!("PanierRadiusDistrib" in $$source)) {
            this["PanierRadiusDistrib"] = (new AnimationCurve());
        }
        if (!("PanierRadiusDistribGroups" in $$source)) {
            this["PanierRadiusDistribGroups"] = [];
        }
        if (!("PanierForce" in $$source)) {
            this["PanierForce"] = 0;
        }
        if (!("PanierForceDistrib" in $$source)) {
            this["PanierForceDistrib"] = (new AnimationCurve());
        }
        if (!("PanierStressForce" in $$source)) {
            this["PanierStressForce"] = 0;
        }
        if (!("StressDegreeMin" in $$source)) {
            this["StressDegreeMin"] = 0;
        }
        if (!("StressDegreeMax" in $$source)) {
            this["StressDegreeMax"] = 0;
        }
        if (!("StressMinScale" in $$source)) {
            this["StressMinScale"] = 0;
        }
        if (!("ScaleEaseSpeed" in $$source)) {
            this["ScaleEaseSpeed"] = 0;
        }
        if (!("PanierForceDistanceThreshold" in $$source)) {
            this["PanierForceDistanceThreshold"] = 0;
        }
        if (!("CalcTime" in $$source)) {
            this["CalcTime"] = 0;
        }
        if (!("VelocityForceRate" in $$source)) {
            this["VelocityForceRate"] = 0;
        }
        if (!("VelocityForceRateDistrib" in $$source)) {
            this["VelocityForceRateDistrib"] = (new AnimationCurve());
        }
        if (!("Gravity" in $$source)) {
            this["Gravity"] = (new Vector3());
        }
        if (!("GravityDistrib" in $$source)) {
            this["GravityDistrib"] = (new AnimationCurve());
        }
        if (!("HardValues" in $$source)) {
            this["HardValues"] = Array.from({ length: 4 }, () => 0);
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Psk instance from a string or object.
     */
    static createFrom($$source: any = {}): Psk {
        const $$createField3_0 = $$createType4;
        const $$createField4_0 = $$createType6;
        const $$createField6_0 = $$createType4;
        const $$createField15_0 = $$createType4;
        const $$createField16_0 = $$createType7;
        const $$createField17_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("PanierRadiusDistrib" in $$parsedSource) {
            $$parsedSource["PanierRadiusDistrib"] = $$createField3_0($$parsedSource["PanierRadiusDistrib"]);
        }
        if ("PanierRadiusDistribGroups" in $$parsedSource) {
            $$parsedSource["PanierRadiusDistribGroups"] = $$createField4_0($$parsedSource["PanierRadiusDistribGroups"]);
        }
        if ("PanierForceDistrib" in $$parsedSource) {
            $$parsedSource["PanierForceDistrib"] = $$createField6_0($$parsedSource["PanierForceDistrib"]);
        }
        if ("VelocityForceRateDistrib" in $$parsedSource) {
            $$parsedSource["VelocityForceRateDistrib"] = $$createField15_0($$parsedSource["VelocityForceRateDistrib"]);
        }
        if ("Gravity" in $$parsedSource) {
            $$parsedSource["Gravity"] = $$createField16_0($$parsedSource["Gravity"]);
        }
        if ("GravityDistrib" in $$parsedSource) {
            $$parsedSource["GravityDistrib"] = $$createField17_0($$parsedSource["GravityDistrib"]);
        }
        return new Psk($$parsedSource as Partial<Psk>);
    }
}

/**
 * Vector3 表示三维向量
 * Vector3 represents a three-dimensional vector
 */
export class Vector3 {
    /**
     * X 轴分量 / X-axis component
     */
    "X": number;

    /**
     * Y 轴分量 / Y-axis component
     */
    "Y": number;

    /**
     * Z 轴分量 / Z-axis component
     */
    "Z": number;

    /** Creates a new Vector3 instance. */
    constructor($$source: Partial<Vector3> = {}) {
        if (!("X" in $$source)) {
            this["X"] = 0;
        }
        if (!("Y" in $$source)) {
            this["Y"] = 0;
        }
        if (!("Z" in $$source)) {
            this["Z"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Vector3 instance from a string or object.
     */
    static createFrom($$source: any = {}): Vector3 {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Vector3($$parsedSource as Partial<Vector3>);
    }
}

// Private type creation functions
const $$createType0 = Keyframe.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = AnimationCurve.createFrom;
const $$createType5 = PanierRadiusGroup.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = Vector3.createFrom;
