// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DB2ConfService 专门处理 .db2conf 文件 / DB2ConfService handles .db2conf files
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as KCES$0 from "../../serialization/KCES/models.js";

/**
 * ConvertDB2ConfToJson 将 .db2conf 文件转换为编辑 JSON
 * ConvertDB2ConfToJson converts a .db2conf file to editing JSON
 */
export function ConvertDB2ConfToJson(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(3339538024, inputPath, outputPath, maxOutputBytes);
}

/**
 * ConvertJsonToDB2Conf 将编辑 JSON 转换为 .db2conf 文件
 * ConvertJsonToDB2Conf converts editing JSON to a .db2conf file
 */
export function ConvertJsonToDB2Conf(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(273680506, inputPath, outputPath, maxOutputBytes);
}

/**
 * ReadDB2ConfFile 读取并解码 .db2conf 文件
 * ReadDB2ConfFile reads and decodes a .db2conf file
 */
export function ReadDB2ConfFile(path: string): $CancellablePromise<KCES$0.MagicaClothSerializeData | null> {
    return $Call.ByID(2334114292, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * WriteDB2ConfFile 编码并写入 .db2conf 文件
 * WriteDB2ConfFile encodes and writes a .db2conf file
 */
export function WriteDB2ConfFile(path: string, value: KCES$0.MagicaClothSerializeData | null): $CancellablePromise<void> {
    return $Call.ByID(2102238685, path, value);
}

// Private type creation functions
const $$createType0 = KCES$0.MagicaClothSerializeData.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
