// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DBConfService 专门处理 .dbconf 文件 / DBConfService handles .dbconf files
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as KCES$0 from "../../serialization/KCES/models.js";

/**
 * ConvertDBConfToJson 将 .dbconf 文件转换为编辑 JSON
 * ConvertDBConfToJson converts a .dbconf file to editing JSON
 */
export function ConvertDBConfToJson(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(623317768, inputPath, outputPath, maxOutputBytes);
}

/**
 * ConvertJsonToDBConf 将编辑 JSON 转换为 .dbconf 文件
 * ConvertJsonToDBConf converts editing JSON to a .dbconf file
 */
export function ConvertJsonToDBConf(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(861020956, inputPath, outputPath, maxOutputBytes);
}

/**
 * ReadDBConfFile 读取并解码 .dbconf 文件
 * ReadDBConfFile reads and decodes a .dbconf file
 */
export function ReadDBConfFile(path: string): $CancellablePromise<KCES$0.DynamicBoneStatus | null> {
    return $Call.ByID(2274343362, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * WriteDBConfFile 编码并写入 .dbconf 文件
 * WriteDBConfFile encodes and writes a .dbconf file
 */
export function WriteDBConfFile(path: string, value: KCES$0.DynamicBoneStatus | null): $CancellablePromise<void> {
    return $Call.ByID(4060466445, path, value);
}

// Private type creation functions
const $$createType0 = KCES$0.DynamicBoneStatus.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
