// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DBColService 专门处理 .dbcol 文件 / DBColService handles .dbcol files
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as KCES$0 from "../../serialization/KCES/models.js";

/**
 * ConvertDBColToJson 将 .dbcol 文件转换为编辑 JSON
 * ConvertDBColToJson converts a .dbcol file to editing JSON
 */
export function ConvertDBColToJson(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(3985979408, inputPath, outputPath, maxOutputBytes);
}

/**
 * ConvertJsonToDBCol 将编辑 JSON 转换为 .dbcol 文件
 * ConvertJsonToDBCol converts editing JSON to a .dbcol file
 */
export function ConvertJsonToDBCol(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(2479003550, inputPath, outputPath, maxOutputBytes);
}

/**
 * ReadDBColFile 读取并解码 .dbcol 文件
 * ReadDBColFile reads and decodes a .dbcol file
 */
export function ReadDBColFile(path: string): $CancellablePromise<KCES$0.ColliderPackage | null> {
    return $Call.ByID(2090921784, path);
}

/**
 * WriteDBColFile 编码并写入 .dbcol 文件
 * WriteDBColFile encodes and writes a .dbcol file
 */
export function WriteDBColFile(path: string, value: KCES$0.ColliderPackage | null): $CancellablePromise<void> {
    return $Call.ByID(319112041, path, value);
}
