// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DSB2ConfService 专门处理 .dsb2conf 文件 / DSB2ConfService handles .dsb2conf files
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as KCES$0 from "../../serialization/KCES/models.js";

/**
 * ConvertDSB2ConfToJson 将 .dsb2conf 文件转换为编辑 JSON
 * ConvertDSB2ConfToJson converts a .dsb2conf file to editing JSON
 */
export function ConvertDSB2ConfToJson(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(606123798, inputPath, outputPath, maxOutputBytes);
}

/**
 * ConvertJsonToDSB2Conf 将编辑 JSON 转换为 .dsb2conf 文件
 * ConvertJsonToDSB2Conf converts editing JSON to a .dsb2conf file
 */
export function ConvertJsonToDSB2Conf(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(957659218, inputPath, outputPath, maxOutputBytes);
}

/**
 * ReadDSB2ConfFile 读取并解码 .dsb2conf 文件
 * ReadDSB2ConfFile reads and decodes a .dsb2conf file
 */
export function ReadDSB2ConfFile(path: string): $CancellablePromise<KCES$0.MagicaClothSerializeData | null> {
    return $Call.ByID(2798046370, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * WriteDSB2ConfFile 编码并写入 .dsb2conf 文件
 * WriteDSB2ConfFile encodes and writes a .dsb2conf file
 */
export function WriteDSB2ConfFile(path: string, value: KCES$0.MagicaClothSerializeData | null): $CancellablePromise<void> {
    return $Call.ByID(2883358827, path, value);
}

// Private type creation functions
const $$createType0 = KCES$0.MagicaClothSerializeData.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
