// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DSLColService 专门处理 .dslcol 文件 / DSLColService handles .dslcol files
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as KCES$0 from "../../serialization/KCES/models.js";

/**
 * ConvertDSLColToJson 将 .dslcol 文件转换为编辑 JSON
 * ConvertDSLColToJson converts a .dslcol file to editing JSON
 */
export function ConvertDSLColToJson(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(322317502, inputPath, outputPath, maxOutputBytes);
}

/**
 * ConvertJsonToDSLCol 将编辑 JSON 转换为 .dslcol 文件
 * ConvertJsonToDSLCol converts editing JSON to a .dslcol file
 */
export function ConvertJsonToDSLCol(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(711688330, inputPath, outputPath, maxOutputBytes);
}

/**
 * ReadDSLColFile 读取并解码 .dslcol 文件
 * ReadDSLColFile reads and decodes a .dslcol file
 */
export function ReadDSLColFile(path: string): $CancellablePromise<KCES$0.ColliderPackage | null> {
    return $Call.ByID(2365665546, path);
}

/**
 * WriteDSLColFile 编码并写入 .dslcol 文件
 * WriteDSLColFile encodes and writes a .dslcol file
 */
export function WriteDSLColFile(path: string, value: KCES$0.ColliderPackage | null): $CancellablePromise<void> {
    return $Call.ByID(1520464803, path, value);
}
