// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HitCheckService 专门处理 .hitcheck 文件 / HitCheckService handles .hitcheck files
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as KCES$0 from "../../serialization/KCES/models.js";

/**
 * ConvertHitCheckToJson 将 .hitcheck 文件转换为编辑 JSON
 * ConvertHitCheckToJson converts a .hitcheck file to editing JSON
 */
export function ConvertHitCheckToJson(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(1952999862, inputPath, outputPath, maxOutputBytes);
}

/**
 * ConvertJsonToHitCheck 将编辑 JSON 转换为 .hitcheck 文件
 * ConvertJsonToHitCheck converts editing JSON to a .hitcheck file
 */
export function ConvertJsonToHitCheck(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(2010068090, inputPath, outputPath, maxOutputBytes);
}

/**
 * ReadHitCheckFile 读取并解码 .hitcheck 文件
 * ReadHitCheckFile reads and decodes a .hitcheck file
 */
export function ReadHitCheckFile(path: string): $CancellablePromise<KCES$0.HitCheck | null> {
    return $Call.ByID(692001202, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * WriteHitCheckFile 编码并写入 .hitcheck 文件
 * WriteHitCheckFile encodes and writes a .hitcheck file
 */
export function WriteHitCheckFile(path: string, value: KCES$0.HitCheck | null): $CancellablePromise<void> {
    return $Call.ByID(3134397819, path, value);
}

// Private type creation functions
const $$createType0 = KCES$0.HitCheck.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
