// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * IKColService 专门处理 .ikcol 文件 / IKColService handles .ikcol files
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as KCES$0 from "../../serialization/KCES/models.js";

/**
 * ConvertIKColToJson 将 .ikcol 文件转换为编辑 JSON
 * ConvertIKColToJson converts a .ikcol file to editing JSON
 */
export function ConvertIKColToJson(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(3603364776, inputPath, outputPath, maxOutputBytes);
}

/**
 * ConvertJsonToIKCol 将编辑 JSON 转换为 .ikcol 文件
 * ConvertJsonToIKCol converts editing JSON to a .ikcol file
 */
export function ConvertJsonToIKCol(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(3621219990, inputPath, outputPath, maxOutputBytes);
}

/**
 * ReadIKColFile 读取并解码 .ikcol 文件
 * ReadIKColFile reads and decodes a .ikcol file
 */
export function ReadIKColFile(path: string): $CancellablePromise<KCES$0.IKColliderPackage | null> {
    return $Call.ByID(1891670120, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * WriteIKColFile 编码并写入 .ikcol 文件
 * WriteIKColFile encodes and writes a .ikcol file
 */
export function WriteIKColFile(path: string, value: KCES$0.IKColliderPackage | null): $CancellablePromise<void> {
    return $Call.ByID(10792957, path, value);
}

// Private type creation functions
const $$createType0 = KCES$0.IKColliderPackage.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
