// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LimbColService 专门处理 .limbcol 文件 / LimbColService handles .limbcol files
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as KCES$0 from "../../serialization/KCES/models.js";

/**
 * ConvertJsonToLimbCol 将编辑 JSON 转换为 .limbcol 文件
 * ConvertJsonToLimbCol converts editing JSON to a .limbcol file
 */
export function ConvertJsonToLimbCol(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(1307459766, inputPath, outputPath, maxOutputBytes);
}

/**
 * ConvertLimbColToJson 将 .limbcol 文件转换为编辑 JSON
 * ConvertLimbColToJson converts a .limbcol file to editing JSON
 */
export function ConvertLimbColToJson(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(1313407448, inputPath, outputPath, maxOutputBytes);
}

/**
 * ReadLimbColFile 读取并解码 .limbcol 文件
 * ReadLimbColFile reads and decodes a .limbcol file
 */
export function ReadLimbColFile(path: string): $CancellablePromise<KCES$0.LimbColliderPackage | null> {
    return $Call.ByID(4224393080, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * WriteLimbColFile 编码并写入 .limbcol 文件
 * WriteLimbColFile encodes and writes a .limbcol file
 */
export function WriteLimbColFile(path: string, value: KCES$0.LimbColliderPackage | null): $CancellablePromise<void> {
    return $Call.ByID(3772855533, path, value);
}

// Private type creation functions
const $$createType0 = KCES$0.LimbColliderPackage.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
