// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MaterialAssetsService 专门处理 .materialassets 文件 / MaterialAssetsService handles .materialassets files
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as KCES$0 from "../../serialization/KCES/models.js";

/**
 * ConvertJsonToMaterialAssets 将编辑 JSON 转换为 .materialassets 文件
 * ConvertJsonToMaterialAssets converts editing JSON to a .materialassets file
 */
export function ConvertJsonToMaterialAssets(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(3807795208, inputPath, outputPath, maxOutputBytes);
}

/**
 * ConvertMaterialAssetsToJson 将 .materialassets 文件转换为编辑 JSON
 * ConvertMaterialAssetsToJson converts a .materialassets file to editing JSON
 */
export function ConvertMaterialAssetsToJson(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(576884120, inputPath, outputPath, maxOutputBytes);
}

/**
 * ReadMaterialAssetsFile 读取并解码 .materialassets 文件
 * ReadMaterialAssetsFile reads and decodes a .materialassets file
 */
export function ReadMaterialAssetsFile(path: string): $CancellablePromise<KCES$0.MaterialAssets | null> {
    return $Call.ByID(4070260774, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * WriteMaterialAssetsFile 编码并写入 .materialassets 文件
 * WriteMaterialAssetsFile encodes and writes a .materialassets file
 */
export function WriteMaterialAssetsFile(path: string, value: KCES$0.MaterialAssets | null): $CancellablePromise<void> {
    return $Call.ByID(2084995293, path, value);
}

// Private type creation functions
const $$createType0 = KCES$0.MaterialAssets.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
