// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MenuAssetsService 专门处理 .menuassets 文件 / MenuAssetsService handles .menuassets files
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as KCES$0 from "../../serialization/KCES/models.js";

/**
 * ConvertJsonToMenuAssets 将编辑 JSON 转换为 .menuassets 文件
 * ConvertJsonToMenuAssets converts editing JSON to a .menuassets file
 */
export function ConvertJsonToMenuAssets(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(1769014360, inputPath, outputPath, maxOutputBytes);
}

/**
 * ConvertMenuAssetsToJson 将 .menuassets 文件转换为编辑 JSON
 * ConvertMenuAssetsToJson converts a .menuassets file to editing JSON
 */
export function ConvertMenuAssetsToJson(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(2998098400, inputPath, outputPath, maxOutputBytes);
}

/**
 * ReadMenuAssetsFile 读取并解码 .menuassets 文件
 * ReadMenuAssetsFile reads and decodes a .menuassets file
 */
export function ReadMenuAssetsFile(path: string): $CancellablePromise<KCES$0.MenuAssets | null> {
    return $Call.ByID(406190846, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * WriteMenuAssetsFile 编码并写入 .menuassets 文件
 * WriteMenuAssetsFile encodes and writes a .menuassets file
 */
export function WriteMenuAssetsFile(path: string, value: KCES$0.MenuAssets | null): $CancellablePromise<void> {
    return $Call.ByID(475048009, path, value);
}

// Private type creation functions
const $$createType0 = KCES$0.MenuAssets.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
