// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NSONService 专门处理 .nson 文件 / NSONService handles .nson files
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as jsontext$0 from "../../../../../../encoding/json/jsontext/models.js";

/**
 * ConvertJsonToNSON 将编辑 JSON 转换为 .nson 文件
 * ConvertJsonToNSON converts editing JSON to a .nson file
 */
export function ConvertJsonToNSON(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(424954112, inputPath, outputPath, maxOutputBytes);
}

/**
 * ConvertNSONToJson 将 .nson 文件转换为编辑 JSON
 * ConvertNSONToJson converts a .nson file to editing JSON
 */
export function ConvertNSONToJson(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(3402871888, inputPath, outputPath, maxOutputBytes);
}

/**
 * ReadNSONFile 读取并解码 .nson 文件
 * ReadNSONFile reads and decodes a .nson file
 */
export function ReadNSONFile(path: string): $CancellablePromise<json$0.RawMessage> {
    return $Call.ByID(2645031846, path);
}

/**
 * WriteNSONFile 编码并写入 .nson 文件
 * WriteNSONFile encodes and writes a .nson file
 */
export function WriteNSONFile(path: string, value: json$0.RawMessage): $CancellablePromise<void> {
    return $Call.ByID(3398301281, path, value);
}
