// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PriorityMaterialAssetsService 专门处理 .pmatassets 文件 / PriorityMaterialAssetsService handles .pmatassets files
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as KCES$0 from "../../serialization/KCES/models.js";

/**
 * ConvertJsonToPriorityMaterialAssets 将编辑 JSON 转换为 .pmatassets 文件
 * ConvertJsonToPriorityMaterialAssets converts editing JSON to a .pmatassets file
 */
export function ConvertJsonToPriorityMaterialAssets(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(2865226104, inputPath, outputPath, maxOutputBytes);
}

/**
 * ConvertPriorityMaterialAssetsToJson 将 .pmatassets 文件转换为编辑 JSON
 * ConvertPriorityMaterialAssetsToJson converts a .pmatassets file to editing JSON
 */
export function ConvertPriorityMaterialAssetsToJson(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(3780711688, inputPath, outputPath, maxOutputBytes);
}

/**
 * ReadPriorityMaterialAssetsFile 读取并解码 .pmatassets 文件
 * ReadPriorityMaterialAssetsFile reads and decodes a .pmatassets file
 */
export function ReadPriorityMaterialAssetsFile(path: string): $CancellablePromise<KCES$0.PriorityMaterialAssets | null> {
    return $Call.ByID(1983349990, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * WritePriorityMaterialAssetsFile 编码并写入 .pmatassets 文件
 * WritePriorityMaterialAssetsFile encodes and writes a .pmatassets file
 */
export function WritePriorityMaterialAssetsFile(path: string, value: KCES$0.PriorityMaterialAssets | null): $CancellablePromise<void> {
    return $Call.ByID(1258470621, path, value);
}

// Private type creation functions
const $$createType0 = KCES$0.PriorityMaterialAssets.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
