// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PskService 专门处理 KCES 使用的 .psk 共用格式 / PskService handles the shared .psk format used by KCES
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as COM3D2$0 from "../../serialization/COM3D2/models.js";

/**
 * ConvertJsonToPsk 将编辑 JSON 转换为 .psk 文件
 * ConvertJsonToPsk converts editing JSON to a .psk file
 */
export function ConvertJsonToPsk(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(441916458, inputPath, outputPath, maxOutputBytes);
}

/**
 * ConvertPskToJson 将 .psk 文件转换为编辑 JSON
 * ConvertPskToJson converts a .psk file to editing JSON
 */
export function ConvertPskToJson(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(3083449928, inputPath, outputPath, maxOutputBytes);
}

/**
 * ReadPskFile 读取 .psk 或 .psk.json 文件
 * ReadPskFile reads a .psk or .psk.json file
 */
export function ReadPskFile(path: string): $CancellablePromise<COM3D2$0.Psk | null> {
    return $Call.ByID(3278741668, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * WritePskFile 编码并写入 .psk 文件
 * WritePskFile encodes and writes a .psk file
 */
export function WritePskFile(path: string, value: COM3D2$0.Psk | null): $CancellablePromise<void> {
    return $Call.ByID(1454914253, path, value);
}

// Private type creation functions
const $$createType0 = COM3D2$0.Psk.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
