// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UndressPartsDataService 专门处理 .undresspdat 文件 / UndressPartsDataService handles .undresspdat files
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as KCES$0 from "../../serialization/KCES/models.js";

/**
 * ConvertJsonToUndressPartsData 将编辑 JSON 转换为 .undresspdat 文件
 * ConvertJsonToUndressPartsData converts editing JSON to a .undresspdat file
 */
export function ConvertJsonToUndressPartsData(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(1831386580, inputPath, outputPath, maxOutputBytes);
}

/**
 * ConvertUndressPartsDataToJson 将 .undresspdat 文件转换为编辑 JSON
 * ConvertUndressPartsDataToJson converts a .undresspdat file to editing JSON
 */
export function ConvertUndressPartsDataToJson(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(3070288360, inputPath, outputPath, maxOutputBytes);
}

/**
 * ReadUndressPartsDataFile 读取并解码 .undresspdat 文件
 * ReadUndressPartsDataFile reads and decodes a .undresspdat file
 */
export function ReadUndressPartsDataFile(path: string): $CancellablePromise<KCES$0.UndressPrecomputeTarget | null> {
    return $Call.ByID(1921331386, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * WriteUndressPartsDataFile 编码并写入 .undresspdat 文件
 * WriteUndressPartsDataFile encodes and writes a .undresspdat file
 */
export function WriteUndressPartsDataFile(path: string, value: KCES$0.UndressPrecomputeTarget | null): $CancellablePromise<void> {
    return $Call.ByID(2554876797, path, value);
}

// Private type creation functions
const $$createType0 = KCES$0.UndressPrecomputeTarget.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
