// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Table 表示解密后的 .nei CSV 表格数据
 * Table represents decrypted .nei CSV table data
 */
export class Table {
    /**
     * CSV 的行数 / Number of CSV rows
     */
    "Rows": number;

    /**
     * CSV 的列数 / Number of CSV columns
     */
    "Cols": number;

    /**
     * CSV 的数据 [行][列] / CSV cell data indexed as [row][column]
     */
    "Data": string[][];

    /**
     * 单元格文本的字符编码，读取时按内容探测，写出时为空等同于 Shift-JIS
     * Character encoding of cell text, detected from content while reading, and an empty value writes as Shift-JIS
     */
    "TextEncoding"?: TextEncoding;

    /** Creates a new Table instance. */
    constructor($$source: Partial<Table> = {}) {
        if (!("Rows" in $$source)) {
            this["Rows"] = 0;
        }
        if (!("Cols" in $$source)) {
            this["Cols"] = 0;
        }
        if (!("Data" in $$source)) {
            this["Data"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Table instance from a string or object.
     */
    static createFrom($$source: any = {}): Table {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Data" in $$parsedSource) {
            $$parsedSource["Data"] = $$createField2_0($$parsedSource["Data"]);
        }
        return new Table($$parsedSource as Partial<Table>);
    }
}

/**
 * TextEncoding 表示 .nei 单元格文本使用的字符编码 / TextEncoding represents the character encoding used by .nei cell text
 */
export enum TextEncoding {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * TextEncodingShiftJIS 是 COM3D2 读取 .nei 时使用的 Shift-JIS（CP932）编码
     * TextEncodingShiftJIS is the Shift-JIS (CP932) encoding COM3D2 uses when reading .nei
     */
    TextEncodingShiftJIS = "Shift-JIS",

    /**
     * TextEncodingUTF8 是 KCES 读取 .nei 时使用的 UTF-8 编码
     * TextEncodingUTF8 is the UTF-8 encoding KCES uses when reading .nei
     */
    TextEncodingUTF8 = "UTF-8",
};

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($$createType0);
