// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App 提供应用级功能：文件对话框、版本检查、文件信息、文件类型识别
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as COM3D2$0 from "../../MeidoSerialization/service/COM3D2/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckLatestVersion 版本检查
 */
export function CheckLatestVersion(): $CancellablePromise<$models.VersionCheckResult> {
    return $Call.ByID(681626834).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CompareVersions 版本号比较，返回 true 表示 localVersion 小于 latestVersion
 */
export function CompareVersions(localVersion: string, latestVersion: string): $CancellablePromise<boolean> {
    return $Call.ByID(657229071, localVersion, latestVersion);
}

/**
 * DetermineFileType 判断 KCES 文件类型；无法识别时 FileType 为 Unknown，前端可按扩展名回退
 */
export function DetermineFileType(path: string): $CancellablePromise<COM3D2$0.FileInfo> {
    return $Call.ByID(3447304086, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetAppVersion 获取应用版本
 */
export function GetAppVersion(): $CancellablePromise<string> {
    return $Call.ByID(1891841056);
}

/**
 * GetEditingSchemas 返回全部格式的编辑 JSON Schema 文本（formatKey → schema JSON），
 * 供前端注册到 Monaco 以获得结构校验、补全与悬停提示。
 * schema 会与 knowledge guide 的字段说明合并（写入各节点 description），
 * 文案按 locale 翻译（zh-CN/ja-JP/ko-KR，未命中回退英文），
 * 并附带认证状态（序列化/源码语义/游戏实测三项独立认证及 AI/人工审核主体）
 */
export function GetEditingSchemas(locale: string): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(1928805721, locale).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetFileSize 获取文件大小
 */
export function GetFileSize(path: string): $CancellablePromise<number> {
    return $Call.ByID(1399140802, path);
}

/**
 * NewStructuredDocument 返回一个格式的合法空文档 JSON 文本，用于新建文件（另存为保存）
 */
export function NewStructuredDocument(formatKey: string): $CancellablePromise<string> {
    return $Call.ByID(3076821661, formatKey);
}

/**
 * ReadStructuredFile 读取原生文件并以 JSON 文本返回结构化数据。
 * 走字符串通道以保留 uint64 等大整数的精度（前端用 lossless 解析）
 */
export function ReadStructuredFile(formatKey: string, path: string): $CancellablePromise<string> {
    return $Call.ByID(617754950, formatKey, path);
}

/**
 * ReadTextFile 读取 UTF-8 文本文件（用于编辑 JSON），自动去除 BOM
 */
export function ReadTextFile(path: string): $CancellablePromise<string> {
    return $Call.ByID(4291257694, path);
}

/**
 * SelectDirectory 选择一个文件夹，返回用户选择的路径，用户取消时返回空字符串
 */
export function SelectDirectory(title: string): $CancellablePromise<string> {
    return $Call.ByID(2605628586, title);
}

/**
 * SelectFile 选择需要处理的文件，返回用户选择的文件路径，用户取消时返回空字符串
 * filetype 形如 "*.menuassets;*.menuassets.json"
 */
export function SelectFile(filetype: string, fileDisplayName: string): $CancellablePromise<string> {
    return $Call.ByID(2533574405, filetype, fileDisplayName);
}

/**
 * SelectPathToSave 选择一个路径保存文件，返回用户选择的路径，用户取消时返回空字符串
 */
export function SelectPathToSave(filetype: string, fileDisplayName: string): $CancellablePromise<string> {
    return $Call.ByID(3286775384, filetype, fileDisplayName);
}

export function SetApplication(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(724352193, app);
}

/**
 * StartupFile 返回通过文件关联传入的文件路径
 */
export function StartupFile(): $CancellablePromise<string> {
    return $Call.ByID(329404922);
}

/**
 * WriteStructuredFile 将编辑 JSON 文本解码为具体结构并写入原生文件
 */
export function WriteStructuredFile(formatKey: string, path: string, jsonText: string): $CancellablePromise<void> {
    return $Call.ByID(526224575, formatKey, path, jsonText);
}

/**
 * WriteTextFile 写入 UTF-8 文本文件（用于编辑 JSON）
 */
export function WriteTextFile(path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(2693203579, path, content);
}

// Private type creation functions
const $$createType0 = $models.VersionCheckResult.createFrom;
const $$createType1 = COM3D2$0.FileInfo.createFrom;
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
