// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ProtocolStatus 是自定义协议的当前状态，设置页用它说明协议现在能不能用
 * ProtocolStatus is the current state of the custom protocol so the settings page can explain whether it works
 */
export class ProtocolStatus {
    /**
     * 协议名，不含 :// / Scheme name without ://
     */
    "scheme": string;

    /**
     * 系统上是否注册过 / Whether it is registered on this system
     */
    "registered": boolean;

    /** Creates a new ProtocolStatus instance. */
    constructor($$source: Partial<ProtocolStatus> = {}) {
        if (!("scheme" in $$source)) {
            this["scheme"] = "";
        }
        if (!("registered" in $$source)) {
            this["registered"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProtocolStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ProtocolStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProtocolStatus($$parsedSource as Partial<ProtocolStatus>);
    }
}

/**
 * Settings 是必须在应用启动前就读到的配置
 * 单实例要在 application.New 时决定，那时前端还没起来，localStorage 读不到，所以这类设置存文件
 * Settings holds configuration that must be known before the application starts
 * Single instance is decided at application.New, before the frontend exists, so localStorage is unavailable and these settings live in a file
 */
export class Settings {
    /**
     * SingleInstance 为 true 时只允许一个实例运行，协议唤起与文件关联都转交给已有窗口
     * 关闭后每次唤起都会开新窗口，冷启动仍能打开目标文件
     * When true only one instance runs and protocol or association opens are handed to the existing window
     * When off each invocation opens another window, which still opens the target file on cold start
     */
    "singleInstance": boolean;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("singleInstance" in $$source)) {
            this["singleInstance"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

/**
 * Texture2DInfo 独立 Texture2D 主文件的元数据
 */
export class Texture2DInfo {
    /**
     * Unity 资源名 / Unity asset name
     */
    "name": string;

    /**
     * 宽 / Width
     */
    "width": number;

    /**
     * 高 / Height
     */
    "height": number;

    /**
     * Unity TextureFormat 枚举值 / Unity TextureFormat enum value
     */
    "textureFormat": number;

    /**
     * TextureFormat 的可读名称 / Readable TextureFormat name
     */
    "formatName": string;

    /**
     * mipmap 层数 / Mipmap count
     */
    "mipCount": number;

    /**
     * 内联像素数据大小 / Inline pixel data size
     */
    "inlineBytes": number;

    /**
     * 外部 .resS 引用路径，内联时为空 / External .resS path, empty when inline
     */
    "streamPath": string;

    /**
     * 外部引用数据大小 / External payload size
     */
    "streamBytes": number;

    /** Creates a new Texture2DInfo instance. */
    constructor($$source: Partial<Texture2DInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("textureFormat" in $$source)) {
            this["textureFormat"] = 0;
        }
        if (!("formatName" in $$source)) {
            this["formatName"] = "";
        }
        if (!("mipCount" in $$source)) {
            this["mipCount"] = 0;
        }
        if (!("inlineBytes" in $$source)) {
            this["inlineBytes"] = 0;
        }
        if (!("streamPath" in $$source)) {
            this["streamPath"] = "";
        }
        if (!("streamBytes" in $$source)) {
            this["streamBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Texture2DInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): Texture2DInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Texture2DInfo($$parsedSource as Partial<Texture2DInfo>);
    }
}

/**
 * Texture2DPreview 预览用的 base64 图像
 */
export class Texture2DPreview {
    /**
     * 图像 MIME 类型 / Image MIME type
     */
    "mime": string;

    /**
     * base64 编码的图像数据 / Base64-encoded image data
     */
    "base64": string;

    /** Creates a new Texture2DPreview instance. */
    constructor($$source: Partial<Texture2DPreview> = {}) {
        if (!("mime" in $$source)) {
            this["mime"] = "";
        }
        if (!("base64" in $$source)) {
            this["base64"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Texture2DPreview instance from a string or object.
     */
    static createFrom($$source: any = {}): Texture2DPreview {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Texture2DPreview($$parsedSource as Partial<Texture2DPreview>);
    }
}

/**
 * VersionCheckResult 版本检查结果
 */
export class VersionCheckResult {
    "CurrentVersion": string;
    "LatestVersion": string;
    "IsNewer": boolean;

    /** Creates a new VersionCheckResult instance. */
    constructor($$source: Partial<VersionCheckResult> = {}) {
        if (!("CurrentVersion" in $$source)) {
            this["CurrentVersion"] = "";
        }
        if (!("LatestVersion" in $$source)) {
            this["LatestVersion"] = "";
        }
        if (!("IsNewer" in $$source)) {
            this["IsNewer"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VersionCheckResult instance from a string or object.
     */
    static createFrom($$source: any = {}): VersionCheckResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VersionCheckResult($$parsedSource as Partial<VersionCheckResult>);
    }
}
