// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Texture2DService 提供 KCES Texture2D 的识别、元数据、预览与图像互转
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckImageMagick 报告是否装有 ImageMagick；PNG 预览与 PNG 导出依赖它，DDS 导出不依赖
 */
export function CheckImageMagick(): $CancellablePromise<boolean> {
    return $Call.ByID(2919037691);
}

/**
 * CopyTexture2DFile 原样复制独立 Texture2D 主文件，用于没有改动时的「另存为」，避免重编码丢掉压缩格式与 mipmap
 */
export function CopyTexture2DFile(sourcePath: string, targetPath: string): $CancellablePromise<void> {
    return $Call.ByID(1920990934, sourcePath, targetPath);
}

/**
 * ExportTexture2DImage 把独立 Texture2D 主文件导出为 png 或 dds，不改动源文件
 * format 为空时按 outputPath 的扩展名决定
 */
export function ExportTexture2DImage(inputPath: string, outputPath: string, format: string): $CancellablePromise<void> {
    return $Call.ByID(2158821170, inputPath, outputPath, format);
}

/**
 * FileExists 判断普通文件是否存在，供「快速导出同名文件」在覆盖前确认
 */
export function FileExists(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(3618247556, path);
}

/**
 * ImportImageAsTexture2D 用 PNG/JPEG 图像重建独立 Texture2D 主文件
 * 
 * 库的实现是内联单 mip RGBA32，资源名按 outputPath 的文件名推断，
 * 所以写回原路径时资源名保持不变，但原本的压缩格式（DXT5 等）与 mipmap 会丢失。
 */
export function ImportImageAsTexture2D(imagePath: string, outputPath: string): $CancellablePromise<void> {
    return $Call.ByID(117734425, imagePath, outputPath);
}

/**
 * IsTexture2DFile 判断路径是否为带内嵌 TypeTree 的独立 Texture2D 主文件（按内容判断，不看扩展名）
 */
export function IsTexture2DFile(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(447402113, path);
}

/**
 * PreviewImage 读取普通图像文件并以 base64 返回，用于「图像 → Texture2D」方向的预览
 */
export function PreviewImage(path: string): $CancellablePromise<$models.Texture2DPreview> {
    return $Call.ByID(1331931651, path).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * PreviewTexture2D 把独立 Texture2D 主文件转成 PNG 并以 base64 返回，供界面预览（需要 ImageMagick）
 */
export function PreviewTexture2D(path: string): $CancellablePromise<$models.Texture2DPreview> {
    return $Call.ByID(4281608903, path).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ReadTexture2DInfo 读取独立 Texture2D 主文件的元数据
 */
export function ReadTexture2DInfo(path: string): $CancellablePromise<$models.Texture2DInfo> {
    return $Call.ByID(1317194703, path).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Texture2DPreview.createFrom;
const $$createType1 = $models.Texture2DInfo.createFrom;
