// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * VersionCheckResult 版本检查结果
 */
export class VersionCheckResult {
    "CurrentVersion": string;
    "LatestVersion": string;
    "IsNewer": boolean;

    /** Creates a new VersionCheckResult instance. */
    constructor($$source: Partial<VersionCheckResult> = {}) {
        if (!("CurrentVersion" in $$source)) {
            this["CurrentVersion"] = "";
        }
        if (!("LatestVersion" in $$source)) {
            this["LatestVersion"] = "";
        }
        if (!("IsNewer" in $$source)) {
            this["IsNewer"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VersionCheckResult instance from a string or object.
     */
    static createFrom($$source: any = {}): VersionCheckResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VersionCheckResult($$parsedSource as Partial<VersionCheckResult>);
    }
}
