// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FileInfo 用于表示文件类型的结构
 */
export class FileInfo {
    /**
     * 文件类型名称
     */
    "FileType": string;

    /**
     * 用于区分二进制和 JSON 格式 binary/json，见顶部常量定义
     */
    "StorageFormat": string;

    /**
     * 游戏名称 COM3D2/KCES，见顶部常量定义
     */
    "Game": string;

    /**
     * 文件签名
     */
    "Signature": string;

    /**
     * 文件版本
     */
    "Version": number;

    /**
     * 文件路径
     */
    "Path": string;

    /**
     * 文件大小
     */
    "Size": number;

    /** Creates a new FileInfo instance. */
    constructor($$source: Partial<FileInfo> = {}) {
        if (!("FileType" in $$source)) {
            this["FileType"] = "";
        }
        if (!("StorageFormat" in $$source)) {
            this["StorageFormat"] = "";
        }
        if (!("Game" in $$source)) {
            this["Game"] = "";
        }
        if (!("Signature" in $$source)) {
            this["Signature"] = "";
        }
        if (!("Version" in $$source)) {
            this["Version"] = 0;
        }
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Size" in $$source)) {
            this["Size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): FileInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileInfo($$parsedSource as Partial<FileInfo>);
    }
}
