// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DBConfService 专门处理 .dbconf 文件 / DBConfService handles .dbconf files
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as KCES$0 from "../../serialization/KCES/models.js";

/**
 * ConvertDBConfToJson 将 .dbconf 文件转换为编辑 JSON
 * ConvertDBConfToJson converts a .dbconf file to editing JSON
 */
export function ConvertDBConfToJson(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(2728782345, inputPath, outputPath, maxOutputBytes);
}

/**
 * ConvertJsonToDBConf 将编辑 JSON 转换为 .dbconf 文件
 * ConvertJsonToDBConf converts editing JSON to a .dbconf file
 */
export function ConvertJsonToDBConf(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(779657165, inputPath, outputPath, maxOutputBytes);
}

/**
 * ReadDBConfFile 读取并解码 .dbconf 文件
 * ReadDBConfFile reads and decodes a .dbconf file
 */
export function ReadDBConfFile(path: string): $CancellablePromise<KCES$0.KCESPayloadEnvelope | null> {
    return $Call.ByID(1162595073, path);
}

/**
 * WriteDBConfFile 编码并写入 .dbconf 文件
 * WriteDBConfFile encodes and writes a .dbconf file
 */
export function WriteDBConfFile(path: string, value: KCES$0.KCESPayloadEnvelope | null): $CancellablePromise<void> {
    return $Call.ByID(3557520808, path, value);
}
