// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DSBConfService 专门处理 .dsbconf 文件 / DSBConfService handles .dsbconf files
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as KCES$0 from "../../serialization/KCES/models.js";

/**
 * ConvertDSBConfToJson 将 .dsbconf 文件转换为编辑 JSON
 * ConvertDSBConfToJson converts a .dsbconf file to editing JSON
 */
export function ConvertDSBConfToJson(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(1274561177, inputPath, outputPath, maxOutputBytes);
}

/**
 * ConvertJsonToDSBConf 将编辑 JSON 转换为 .dsbconf 文件
 * ConvertJsonToDSBConf converts editing JSON to a .dsbconf file
 */
export function ConvertJsonToDSBConf(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(365902815, inputPath, outputPath, maxOutputBytes);
}

/**
 * ReadDSBConfFile 读取并解码 .dsbconf 文件
 * ReadDSBConfFile reads and decodes a .dsbconf file
 */
export function ReadDSBConfFile(path: string): $CancellablePromise<KCES$0.KCESPayloadEnvelope | null> {
    return $Call.ByID(1536024457, path);
}

/**
 * WriteDSBConfFile 编码并写入 .dsbconf 文件
 * WriteDSBConfFile encodes and writes a .dsbconf file
 */
export function WriteDSBConfFile(path: string, value: KCES$0.KCESPayloadEnvelope | null): $CancellablePromise<void> {
    return $Call.ByID(486639248, path, value);
}
