// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DSL2ConfService 专门处理 .dsl2conf 文件 / DSL2ConfService handles .dsl2conf files
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as KCES$0 from "../../serialization/KCES/models.js";

/**
 * ConvertDSL2ConfToJson 将 .dsl2conf 文件转换为编辑 JSON
 * ConvertDSL2ConfToJson converts a .dsl2conf file to editing JSON
 */
export function ConvertDSL2ConfToJson(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(60875231, inputPath, outputPath, maxOutputBytes);
}

/**
 * ConvertJsonToDSL2Conf 将编辑 JSON 转换为 .dsl2conf 文件
 * ConvertJsonToDSL2Conf converts editing JSON to a .dsl2conf file
 */
export function ConvertJsonToDSL2Conf(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(771648947, inputPath, outputPath, maxOutputBytes);
}

/**
 * ReadDSL2ConfFile 读取并解码 .dsl2conf 文件
 * ReadDSL2ConfFile reads and decodes a .dsl2conf file
 */
export function ReadDSL2ConfFile(path: string): $CancellablePromise<KCES$0.KCESPayloadEnvelope | null> {
    return $Call.ByID(837540765, path);
}

/**
 * WriteDSL2ConfFile 编码并写入 .dsl2conf 文件
 * WriteDSL2ConfFile encodes and writes a .dsl2conf file
 */
export function WriteDSL2ConfFile(path: string, value: KCES$0.KCESPayloadEnvelope | null): $CancellablePromise<void> {
    return $Call.ByID(4110336010, path, value);
}
