// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DSLConfService 专门处理 .dslconf 文件 / DSLConfService handles .dslconf files
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as KCES$0 from "../../serialization/KCES/models.js";

/**
 * ConvertDSLConfToJson 将 .dslconf 文件转换为编辑 JSON
 * ConvertDSLConfToJson converts a .dslconf file to editing JSON
 */
export function ConvertDSLConfToJson(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(773013173, inputPath, outputPath, maxOutputBytes);
}

/**
 * ConvertJsonToDSLConf 将编辑 JSON 转换为 .dslconf 文件
 * ConvertJsonToDSLConf converts editing JSON to a .dslconf file
 */
export function ConvertJsonToDSLConf(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(3816823787, inputPath, outputPath, maxOutputBytes);
}

/**
 * ReadDSLConfFile 读取并解码 .dslconf 文件
 * ReadDSLConfFile reads and decodes a .dslconf file
 */
export function ReadDSLConfFile(path: string): $CancellablePromise<KCES$0.KCESPayloadEnvelope | null> {
    return $Call.ByID(2412034997, path);
}

/**
 * WriteDSLConfFile 编码并写入 .dslconf 文件
 * WriteDSLConfFile encodes and writes a .dslconf file
 */
export function WriteDSLConfFile(path: string, value: KCES$0.KCESPayloadEnvelope | null): $CancellablePromise<void> {
    return $Call.ByID(3956893032, path, value);
}
