// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * IKColBytesService 专门处理 .ikcol.bytes 文件 / IKColBytesService handles .ikcol.bytes files
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as KCES$0 from "../../serialization/KCES/models.js";

/**
 * ConvertIKColBytesToJson 将 .ikcol.bytes 文件转换为编辑 JSON
 * ConvertIKColBytesToJson converts a .ikcol.bytes file to editing JSON
 */
export function ConvertIKColBytesToJson(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(2647374675, inputPath, outputPath, maxOutputBytes);
}

/**
 * ConvertJsonToIKColBytes 将编辑 JSON 转换为 .ikcol.bytes 文件
 * ConvertJsonToIKColBytes converts editing JSON to a .ikcol.bytes file
 */
export function ConvertJsonToIKColBytes(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(1037237015, inputPath, outputPath, maxOutputBytes);
}

/**
 * ReadIKColBytesFile 读取并解码 .ikcol.bytes 文件
 * ReadIKColBytesFile reads and decodes a .ikcol.bytes file
 */
export function ReadIKColBytesFile(path: string): $CancellablePromise<KCES$0.KCESPayloadEnvelope | null> {
    return $Call.ByID(3368549449, path);
}

/**
 * WriteIKColBytesFile 编码并写入 .ikcol.bytes 文件
 * WriteIKColBytesFile encodes and writes a .ikcol.bytes file
 */
export function WriteIKColBytesFile(path: string, value: KCES$0.KCESPayloadEnvelope | null): $CancellablePromise<void> {
    return $Call.ByID(920430990, path, value);
}
