// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MaidColliderService 专门处理 maid_collider.bytes 与 maid_collider_touch.bytes 文件 / MaidColliderService handles maid_collider.bytes and maid_collider_touch.bytes files
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as KCES$0 from "../../serialization/KCES/models.js";

/**
 * ConvertJSONToMaidCollider 将编辑 JSON 转换为女仆碰撞体载荷
 * ConvertJSONToMaidCollider converts editing JSON to a maid-collider payload
 */
export function ConvertJSONToMaidCollider(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(2448407423, inputPath, outputPath, maxOutputBytes);
}

/**
 * ConvertMaidColliderToJSON 将女仆碰撞体载荷转换为编辑 JSON
 * ConvertMaidColliderToJSON converts a maid-collider payload to editing JSON
 */
export function ConvertMaidColliderToJSON(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(2159086995, inputPath, outputPath, maxOutputBytes);
}

/**
 * ReadMaidColliderFile 读取并解码女仆碰撞体载荷
 * ReadMaidColliderFile reads and decodes a maid-collider payload
 */
export function ReadMaidColliderFile(path: string): $CancellablePromise<KCES$0.MaidColliderFile | null> {
    return $Call.ByID(622847225, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * WriteMaidColliderFile 将女仆胶囊碰撞体结构直接编码并写入原生载荷文件
 * WriteMaidColliderFile directly encodes a maid capsule collider value and writes it to a native payload file
 */
export function WriteMaidColliderFile(path: string, value: KCES$0.MaidColliderFile | null): $CancellablePromise<void> {
    return $Call.ByID(940444986, path, value);
}

// Private type creation functions
const $$createType0 = KCES$0.MaidColliderFile.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
