// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ModelService 专门处理 KCES MessagePack .model 文件 / ModelService handles KCES MessagePack .model files
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as KCES$0 from "../../serialization/KCES/models.js";

/**
 * ConvertGLTFToModel 将 glTF 或 GLB 转换为 .model 与 .mmesh 文件并写入输出目录
 * 文件名优先取自导出时保存的 kcesModel extras，否则从输入文件名小写派生
 * ConvertGLTFToModel converts glTF or GLB into .model and .mmesh files written to the output directory
 * File names prefer the kcesModel extras saved during export and otherwise derive from the lowercased input file name
 */
export function ConvertGLTFToModel(inputPath: string, outputDir: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(3864648038, inputPath, outputDir, maxOutputBytes);
}

/**
 * ConvertJsonToModel 将编辑 JSON 转换为 KCES .model 文件
 * ConvertJsonToModel converts editing JSON to a KCES .model file
 */
export function ConvertJsonToModel(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(3648374955, inputPath, outputPath, maxOutputBytes);
}

/**
 * ConvertModelToGLTF 将 .model 与其引用的 .mmesh 导出为带骨架、蒙皮、变形目标和材质名的完整 glTF 或 GLB
 * KCES 专有字段保存在文档 extras 的 kcesModel 键下，供反向转换无损还原
 * ConvertModelToGLTF exports a .model and its referenced .mmesh to complete glTF or GLB with the skeleton, skin, morph targets, and material names
 * KCES-specific fields are stored under the kcesModel key in document extras so the reverse conversion can restore them losslessly
 */
export function ConvertModelToGLTF(inputPath: string, outputPath: string, format: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(3383278362, inputPath, outputPath, format, maxOutputBytes);
}

/**
 * ConvertModelToJson 将 KCES .model 文件转换为编辑 JSON
 * ConvertModelToJson converts a KCES .model file to editing JSON
 */
export function ConvertModelToJson(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(631165005, inputPath, outputPath, maxOutputBytes);
}

/**
 * ReadModelFile 读取并解码 KCES .model 文件
 * ReadModelFile reads and decodes a KCES .model file
 */
export function ReadModelFile(path: string): $CancellablePromise<KCES$0.Model | null> {
    return $Call.ByID(2403431189, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * WriteModelFile 编码并写入 KCES .model 文件
 * WriteModelFile encodes and writes a KCES .model file
 */
export function WriteModelFile(path: string, value: KCES$0.Model | null): $CancellablePromise<void> {
    return $Call.ByID(2238305664, path, value);
}

// Private type creation functions
const $$createType0 = KCES$0.Model.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
