// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ModelService 专门处理 KCES MessagePack .model 文件 / ModelService handles KCES MessagePack .model files
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as KCES$0 from "../../serialization/KCES/models.js";

/**
 * ConvertJsonToModel 将编辑 JSON 转换为 KCES .model 文件
 * ConvertJsonToModel converts editing JSON to a KCES .model file
 */
export function ConvertJsonToModel(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(3648374955, inputPath, outputPath, maxOutputBytes);
}

/**
 * ConvertModelToJson 将 KCES .model 文件转换为编辑 JSON
 * ConvertModelToJson converts a KCES .model file to editing JSON
 */
export function ConvertModelToJson(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(631165005, inputPath, outputPath, maxOutputBytes);
}

/**
 * ReadModelFile 读取并解码 KCES .model 文件
 * ReadModelFile reads and decodes a KCES .model file
 */
export function ReadModelFile(path: string): $CancellablePromise<KCES$0.Model | null> {
    return $Call.ByID(2403431189, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * WriteModelFile 编码并写入 KCES .model 文件
 * WriteModelFile encodes and writes a KCES .model file
 */
export function WriteModelFile(path: string, value: KCES$0.Model | null): $CancellablePromise<void> {
    return $Call.ByID(2238305664, path, value);
}

// Private type creation functions
const $$createType0 = KCES$0.Model.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
