// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NeiService 专门处理 KCES 使用的 .nei 共用格式 / NeiService handles the shared .nei format used by KCES
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as COM3D2$0 from "../../serialization/COM3D2/models.js";

/**
 * ConvertCSVToNei 将 CSV 转换为 .nei 文件
 * ConvertCSVToNei converts CSV to a .nei file
 */
export function ConvertCSVToNei(inputPath: string, outputPath: string): $CancellablePromise<void> {
    return $Call.ByID(593001645, inputPath, outputPath);
}

/**
 * ConvertNeiToCSV 将 .nei 文件转换为 CSV
 * ConvertNeiToCSV converts a .nei file to CSV
 */
export function ConvertNeiToCSV(inputPath: string, outputPath: string): $CancellablePromise<void> {
    return $Call.ByID(182798273, inputPath, outputPath);
}

/**
 * ReadNeiFile 读取并解码 .nei 文件
 * ReadNeiFile reads and decodes a .nei file
 */
export function ReadNeiFile(path: string): $CancellablePromise<COM3D2$0.Nei | null> {
    return $Call.ByID(4198611759, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * WriteNeiFile 编码并写入 .nei 文件
 * WriteNeiFile encodes and writes a .nei file
 */
export function WriteNeiFile(path: string, value: COM3D2$0.Nei | null): $CancellablePromise<void> {
    return $Call.ByID(3897102556, path, value);
}

// Private type creation functions
const $$createType0 = COM3D2$0.Nei.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
