// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NSONService 专门处理 .nson 文件 / NSONService handles .nson files
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as KCES$0 from "../../serialization/KCES/models.js";

/**
 * ConvertJsonToNSON 将编辑 JSON 转换为 .nson 文件
 * ConvertJsonToNSON converts editing JSON to a .nson file
 */
export function ConvertJsonToNSON(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(747417861, inputPath, outputPath, maxOutputBytes);
}

/**
 * ConvertNSONToJson 将 .nson 文件转换为编辑 JSON
 * ConvertNSONToJson converts a .nson file to editing JSON
 */
export function ConvertNSONToJson(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(4135403885, inputPath, outputPath, maxOutputBytes);
}

/**
 * ReadNSONFile 读取并解码 .nson 文件
 * ReadNSONFile reads and decodes a .nson file
 */
export function ReadNSONFile(path: string): $CancellablePromise<KCES$0.KCESJSONText | null> {
    return $Call.ByID(823870005, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * WriteNSONFile 编码并写入 .nson 文件
 * WriteNSONFile encodes and writes a .nson file
 */
export function WriteNSONFile(path: string, value: KCES$0.KCESJSONText | null): $CancellablePromise<void> {
    return $Call.ByID(1665703680, path, value);
}

// Private type creation functions
const $$createType0 = KCES$0.KCESJSONText.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
