// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PersetService 专门处理 KCES 早期使用且 wire 布局与 .preset 完全相同的 .perset 文件 / PersetService handles the historical KCES .perset files whose wire layout is identical to .preset
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as KCES$0 from "../../serialization/KCES/models.js";

/**
 * ConvertJsonToPerset 将完整展开的编辑 JSON 转换为 KCES .perset 文件
 * ConvertJsonToPerset converts fully expanded editing JSON to a KCES .perset file
 */
export function ConvertJsonToPerset(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(1337531707, inputPath, outputPath, maxOutputBytes);
}

/**
 * ConvertPersetToJson 将 KCES .perset 文件转换为完整展开的编辑 JSON
 * ConvertPersetToJson converts a KCES .perset file to fully expanded editing JSON
 */
export function ConvertPersetToJson(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(2960046115, inputPath, outputPath, maxOutputBytes);
}

/**
 * ReadPersetFile 直接读取并完整展开 KCES .perset 文件中的已知内部块
 * ReadPersetFile directly reads a KCES .perset file and fully expands its known inner blocks
 */
export function ReadPersetFile(path: string): $CancellablePromise<KCES$0.ExpandedKCESPreset | null> {
    return $Call.ByID(2678443365, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * WritePersetFile 直接编码完整展开的 KCES 预设并写入 .perset 文件
 * WritePersetFile directly encodes a fully expanded KCES preset and writes it to a .perset file
 */
export function WritePersetFile(path: string, value: KCES$0.ExpandedKCESPreset | null): $CancellablePromise<void> {
    return $Call.ByID(614362566, path, value);
}

// Private type creation functions
const $$createType0 = KCES$0.ExpandedKCESPreset.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
