// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PresetService 专门处理 KCES 引入的 .preset VirtualDirectory 格式，旧 CM3D2_PRESET 继续由 service/COM3D2 处理 / PresetService handles the KCES .preset VirtualDirectory format while legacy CM3D2_PRESET files remain in service/COM3D2
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as KCES$0 from "../../serialization/KCES/models.js";

/**
 * ConvertJsonToPreset 将完整展开的编辑 JSON 转换为 KCES 预设文件
 * ConvertJsonToPreset converts fully expanded editing JSON to a KCES preset file
 */
export function ConvertJsonToPreset(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(1414391455, inputPath, outputPath, maxOutputBytes);
}

/**
 * ConvertPresetToJson 将 KCES 预设文件转换为完整展开的编辑 JSON
 * ConvertPresetToJson converts a KCES preset file to fully expanded editing JSON
 */
export function ConvertPresetToJson(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(3851750011, inputPath, outputPath, maxOutputBytes);
}

/**
 * ReadPresetFile 读取并完整展开 KCES 预设中的三个已知内部块
 * ReadPresetFile reads a KCES preset and fully expands its three known inner blocks
 */
export function ReadPresetFile(path: string): $CancellablePromise<KCES$0.ExpandedKCESPreset | null> {
    return $Call.ByID(3894479737, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * WritePresetFile 将完整展开的 KCES 预设直接编码并写入 .preset 文件，并为旧调用方分派 .perset 输出
 * WritePresetFile directly encodes a fully expanded KCES preset to .preset while dispatching .perset output for legacy callers
 */
export function WritePresetFile(path: string, value: KCES$0.ExpandedKCESPreset | null): $CancellablePromise<void> {
    return $Call.ByID(3683823810, path, value);
}

// Private type creation functions
const $$createType0 = KCES$0.ExpandedKCESPreset.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
