// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SavedAttachService 在 KCES GP03 SAVED_ATTACH_DATA .sad 文件与带格式标记的编辑 JSON 之间转换 / SavedAttachService converts between KCES GP03 SAVED_ATTACH_DATA .sad files and marker-based editing JSON
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as KCES$0 from "../../serialization/KCES/models.js";

/**
 * ConvertJSONToSavedAttach 将编辑 JSON 转换为原生 .sad 文件
 * ConvertJSONToSavedAttach converts editing JSON to a native .sad file
 */
export function ConvertJSONToSavedAttach(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(1273717895, inputPath, outputPath, maxOutputBytes);
}

/**
 * ConvertSavedAttachToJSON 将原生 .sad 文件转换为编辑 JSON
 * ConvertSavedAttachToJSON converts a native .sad file to editing JSON
 */
export function ConvertSavedAttachToJSON(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(3041699253, inputPath, outputPath, maxOutputBytes);
}

/**
 * ReadSavedAttachFile 读取并解码原生 .sad 文件
 * ReadSavedAttachFile reads and decodes a native .sad file
 */
export function ReadSavedAttachFile(path: string): $CancellablePromise<KCES$0.SavedAttachFile | null> {
    return $Call.ByID(1401132619, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * WriteSavedAttachFile 将保存的附着物结构直接编码并写入 .sad 文件
 * WriteSavedAttachFile directly encodes a saved-attach value and writes it to a .sad file
 */
export function WriteSavedAttachFile(path: string, value: KCES$0.SavedAttachFile | null): $CancellablePromise<void> {
    return $Call.ByID(3157471552, path, value);
}

// Private type creation functions
const $$createType0 = KCES$0.SavedAttachFile.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
