// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UndressDataService 专门处理 .undressdat 文件 / UndressDataService handles .undressdat files
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as KCES$0 from "../../serialization/KCES/models.js";

/**
 * ConvertJsonToUndressData 将编辑 JSON 转换为 .undressdat 文件
 * ConvertJsonToUndressData converts editing JSON to a .undressdat file
 */
export function ConvertJsonToUndressData(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(2652749511, inputPath, outputPath, maxOutputBytes);
}

/**
 * ConvertUndressDataToJson 将 .undressdat 文件转换为编辑 JSON
 * ConvertUndressDataToJson converts a .undressdat file to editing JSON
 */
export function ConvertUndressDataToJson(inputPath: string, outputPath: string, maxOutputBytes: number): $CancellablePromise<void> {
    return $Call.ByID(2947775965, inputPath, outputPath, maxOutputBytes);
}

/**
 * ReadUndressDataFile 读取并解码 .undressdat 文件
 * ReadUndressDataFile reads and decodes a .undressdat file
 */
export function ReadUndressDataFile(path: string): $CancellablePromise<KCES$0.KCESJSONText | null> {
    return $Call.ByID(1451156247, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * WriteUndressDataFile 编码并写入 .undressdat 文件
 * WriteUndressDataFile encodes and writes a .undressdat file
 */
export function WriteUndressDataFile(path: string, value: KCES$0.KCESJSONText | null): $CancellablePromise<void> {
    return $Call.ByID(455391824, path, value);
}

// Private type creation functions
const $$createType0 = KCES$0.KCESJSONText.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
