// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * VirtualDirectoryFraming 标识 MessagePack VirtualDirectory 元数据采用的外层尾部封装 / VirtualDirectoryFraming identifies the outer footer frame used around MessagePack VirtualDirectory metadata
 */
export enum VirtualDirectoryFraming {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * VirtualDirectoryFramingLegacy 使用 0x8e 标记和四字节长度尾部
     * VirtualDirectoryFramingLegacy uses marker 0x8e and a four-byte length footer
     */
    VirtualDirectoryFramingLegacy = 0,

    /**
     * VirtualDirectoryFramingExtended 使用 0xff 标记、八字节长度及固定签名尾部
     * VirtualDirectoryFramingExtended uses marker 0xff, an eight-byte length, and a fixed footer signature
     */
    VirtualDirectoryFramingExtended = 1,
};

/**
 * VirtualDirectoryMetadata 保存子 VirtualDirectory 的真实字段
 * 路径在 ContentTable.Directories 中以规范化的斜杠分隔键保存，解码得到的每个目录都会有条目
 * VirtualDirectoryMetadata stores the real fields of a child VirtualDirectory
 * Paths use canonical slash-separated keys in ContentTable.Directories and every decoded directory has an entry
 */
export class VirtualDirectoryMetadata {
    /**
     * 子 VirtualDirectory 的版本值 / Child VirtualDirectory version value
     */
    "Version": number;

    /** Creates a new VirtualDirectoryMetadata instance. */
    constructor($$source: Partial<VirtualDirectoryMetadata> = {}) {
        if (!("Version" in $$source)) {
            this["Version"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VirtualDirectoryMetadata instance from a string or object.
     */
    static createFrom($$source: any = {}): VirtualDirectoryMetadata {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VirtualDirectoryMetadata($$parsedSource as Partial<VirtualDirectoryMetadata>);
    }
}
